//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_crud.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPost
    {
        public int Id { get; set; }
        public string Post { get; set; }
        public string Writter { get; set; }
        public string Title { get; set; }
    }
}
